version: 0.0
os: linux
files:
  - source: target/hello-jsp.war
    destination: /opt/tomcat/webapps/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
